### ISSUE TITLE
Production Suitability

### ISSUE THREAD

**Issue by prateekrastogi** [myxvisual/react-uwp#1]
Hey, can i run it in production for a small website? Are there any major bugs left unresolved?  I am exploring various ump javascript libraries. Can you suggest some other alternatives that you might have came across?

**Comment by myxvisual** [comment]
Hi @prateekrastogi , thanks for your attention，this project is sitll development. 
sorry, now it can't run in production. 

There are not many bugs，but the docs website is not finished, and some compoents is still devlopement [Todos](https://github.com/myxvisual/react-uwp/blob/master/todo.md).

the new `Fluent Design System` some feature is under schedule. 
if you wan't production your webiste now, you can try [Office UI Fabric](https://dev.office.com/fabric) or [react-winj](https://github.com/winjs/react-winjs)

I am now full-time development of this project.
in this month, will finished lot of component and publish a release version to npm.

If you insist on using it, i can quickly post a version to npm for your.

**Comment by prateekrastogi** [comment]
If you can finish most of the remaining components by this month end, then i would definitely love to use it. My project is going through requirements phase right now. Also, i didn't saw MediaPlayer component in either export modules or To do's list.  I have visited the example site antcores, and the grid views were looking quite beautiful, and MediaPlayer component suggested by UWP guidelines will also enable such grids for multimedia component. For ideas about how those can be used, i would recommend to see semantic ui embed component:  
https://semantic-ui.com/modules/embed.html#/definition 
Semantic-ui also have a react port for the same functionalities.

**Comment by myxvisual** [comment]
It looks awesome.
thanks~ 
MediaPlayer is very interesting components, i will try write some code for  it.

**Comment by myxvisual** [comment]
@prateekrastogi 
Hi, i just add `MediaPlayer` in [docs wesite](https://www.react-uwp.com), and here is [docs](https://www.react-uwp.com/components/mediaplayer).
now, this media have one design mode.
other design mode will update in last few days.

**Comment by prateekrastogi** [comment]
Thanks a lot. Looking forward for the support of player's other design modes, and the remaining unimplemented controls and patterns. Also, nice work for updating the doc to clearly depict the unimplemented elements.

**Comment by myxvisual** [comment]
@prateekrastogi Hi, man, i think this project can be released now, you can check the new the docs website, i add experimental stage fluent design to every components, hope you will like it~
~

**Comment by prateekrastogi** [comment]
@myxvisual  Thanks a lot. I will definitely use it in my forthcoming project.
