### ISSUE TITLE
[Server Side Rendering] Client side styles removing autoprefixes

### ISSUE THREAD

**Issue by renshenhe** [myxvisual/react-uwp#10]
```
warning.js:36 Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) );overflow-y:hidden;" data-reactid="69">
 (server) );overflow-y:hidden;-webkit-transition:a
```
I haven't dove too deep into the style handling of the components but `DropDownMenu` drops prefixes generated by react on the server side when hydrated on the client side`.  Is this potentially a result of `document` object not available on the server side?

- React-UWP: 1.1.0
- React: 15.5.3
- Browser: Chrome 61.0.3159.0 (Official Build) canary (64-bit)

**Comment by myxvisual** [comment]
@renshenhe Do you use `next.js`? i thinking is client and server `navigator.userAgent` is different.

**Comment by renshenhe** [comment]
@myxvisual I am not using next.js and as far as I can tell none of my other dependencies do either.  

```js
// @flow

import React from 'react'
import ReactDOMServer from 'react-dom/server'
import { Provider } from 'react-redux'
import { StaticRouter } from 'react-router'

import initStore from './initStore';
import App from './../shared/App';
import { isProd, APP_CONTAINER_CLASS, STATIC_PATH, WDS_PORT, CLIENT_ID } from '../shared/config';

import Helmet from 'react-helmet';

const renderApp = (location: string, plainPartialState: ?Object, routerContext: ?Object = {}) => {
  const store = initStore(plainPartialState);
  const appHtml = ReactDOMServer.renderToString(
    <Provider store={store}>
      <StaticRouter location={location} context={routerContext}>
        <App />
      </StaticRouter>
    </Provider>
  )

  const head = Helmet.rewind();
  return (
    `<!doctype html>
    <html>
      <head>
        ${head.title}
        ${head.meta}
        <link rel="stylesheet" href="${STATIC_PATH}/css/styles.css">

      </head>
      <body>
        <div class="${APP_CONTAINER_CLASS}">${appHtml}</div>
        <script>
          window.__PRELOADED_STATE__ = ${JSON.stringify(store.getState())}
        </script>
        <script src="${isProd ? STATIC_PATH : `http://localhost:${WDS_PORT}/dist`}/js/bundle.js"></script>
      </body>
    </html>`
    )
}
```
Setup I have is pretty bare.  I am unsure whether it's the `Theme` container's `theme.prepareStyles` not recognizing environment settings but I have not checked it any further.

**Comment by myxvisual** [comment]
@renshenhe if you use SSR, you must provider `navigator.userAgent` to getTheme, because default Theme dosen't have `navigator.usertAgent`.

example code: 

``` jsx
import * as React from "react";

import { Theme as UWPThemeProvider, getTheme } from "react-uwp/Theme";
import Button from "react-uwp/Button";

const theme = getTheme({
  themeName: "dark",
  accent: "#0078D7",
  useFluentDesign: true,
  desktopBackgroundImage: "http://127.0.0.1:8092/static/images/jennifer-bailey-10753.jpg"
  userAgent: req.headers['user-agent']
});

export class App extends React.Component {
  render() {
    return (
      <UWPThemeProvider
        theme={theme}
        needGenerateAcrylic={false} // if using SSR, set this config to false, using fallback color.
      >
        <Button>Server Side Rendering...</Button>
      </UWPThemeProvider>
    )
  }
}

export default App;
```

**Comment by renshenhe** [comment]
@myxvisual Got it thanks for pointing that out.  Closing since it is no longer an issue.

**Comment by prateekrastogi** [comment]
@myxvisual Hi, I am getting the same issue while trying to do it with next.js. I even tried logging the userAgent and output is same on server and browser. What really is intriguing is that if don't pass any styles, then the issue doesn't appear. Any plausible explanation for it?

**Comment by prateekrastogi** [comment]
Hi,
The issue with next.js userAgent not setting in browser was due to it being executed inside getintialprops which executes only once on server rendered app on the server. To overcome it i tried to set the useragent for browser inside the render which correctly sets the useragent but the issue of mismatch in ssr remains. I also tried setting useragent to all. While setting user agent to all  works correctly, but it ignores the root styles passed of flexbox alignment etc. Although, the inline styles are working fine. I guess the issue may be primarily associated with the style attribute flex related components . Some styles like padding, height are working perfectly fine. Is there any workaround you can suggest?

**Comment by prateekrastogi** [comment]
Hi, 
I think the issue is related to the theme.prepareStyle method. If i am wrapping the whole thing in div and using the inline style then everything is working fine. Also, i don't need to use hacky of way acquiring browser userAgent in render method.  Here's the slightly modified relevant code of your next.js example that works perfectly. I think the bug is due to issues in preparestyle


    render() {
        let { userAgent } = this.props

        return (
            <ThemeWrapper
                theme={getTheme({ userAgent: userAgent })}>
                <div style={{
                    padding: '20px 0',
                    minHeight: '100vh',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'space-around'}}>
                <Button>Test Button</Button>
                <DatePicker/>
                <ColorPicker/>
                <ProgressRing size={50}/>
                <p >{userAgent.slice(12)}...</p>
                </div>
            </ThemeWrapper>
        )
    }

**Comment by myxvisual** [comment]
@prateekrastogi i will check the prepareStyle code, thanks for feedback.

**Comment by prateekrastogi** [comment]
Hi,
Fine. Would be nice if you could throw some example in pure js. Right now i am looking at docs code to get the idea about what's the best way to use it. And, the context switch to a typescript really does break the flow. Although, I will been finished with it soon. But, many other potential users would face the similiar problem.
