### ISSUE TITLE
加油！

### ISSUE THREAD

**Issue by Frank1e0927** [myxvisual/react-uwp#15]
非常喜欢你的UIstyle。
但是不知道为什么只有250个star !
加油，坚持！

**Comment by myxvisual** [comment]
@Frank1e0927 谢谢，只要喜欢就可以了，这个项目会持续维护下去的，主要会针对性能的优化，和 React Native 的支持，及开发其他新的组件和案例展示。

**Comment by leedstyh** [comment]
文档最好改进一下。我觉得像 [material ui](http://www.material-ui.com/#/components/app-bar) 这样的挺好，各个component单独一页，在左侧能导航，然后右侧有展示/代码示例/props文档。

**Comment by myxvisual** [comment]
@Frank1e0927 @leedstyh 谢谢支持，现在组件都支持 css-in-js 的样式了，渲染会比之前快很多，不过我没把 inline-style 去除，现在是可以支持 css-in-js 和 inline-style 两种方案。
接下来会对首页重新设计，尽量别那么拥挤。

**Comment by SeedAsh** [comment]
做得这么棒，竟然这么少人知道。看得出作者非常用心，一个人就是一支军队~~
