### ISSUE TITLE
DropDownMenu running onChangeValue despite no changes

### ISSUE THREAD

**Issue by renshenhe** [myxvisual/react-uwp#18]
If you click on the `DropDownMenu` and do not select anything or select the same value it will run the onChange function despite no changes causing unnecessary dispatches/rerenders when using redux.

I tried to remedy the issue by preventing any actions if the value is the same as currently selected:

```js
handleValueChange = val => {
  if (this.state.selectedValue !== val) {
    this.setState({ selectedValue: val })
  }
}
<DropDownMenu
  defaultValue={this.state.selectedValue}
  values={this.state.values}
  onChangeValue={this.handleValueChange}
/>

```

The problem with this approach is that while it does prevent unnecessary `onChangeValue` runs it locks the component in a valueless state when you toggle the component and click _outside_ the options.  Pitfall of not using `<select>`/`<option />`?

**Comment by myxvisual** [comment]
@renshenhe Hi, i think this bug is fixed to `v1.1.3`, forget in the commit record it.
