### ISSUE TITLE
[官网反馈] - demo 站首页轮播组件卡顿

### ISSUE THREAD

**Issue by JayceZhang9602** [myxvisual/react-uwp#2]
### Problem description
demo 站首页轮播组件卡顿 fps30以下
https://www.react-uwp.com/
### Versions
- Browser: Chrome 58 Mac OSX 10.10.6

**Comment by myxvisual** [comment]
![img](http://ora3usaxk.bkt.clouddn.com/issues-%232.JPG)
刚刚看了下 performance，发现页面加载后轮播挺正常的，主要卡顿发生在于 youtube 加载 iframe 时候的 js 抛出的错误，和一开始渲染 acrylic 贴图的时候。
完全加载完并不会卡顿，youtube 的错误可能跟网络有关， 也有可能是 [Youtube iframe API](https://github.com/CookPete/react-player/issues/96) 问题。

**Comment by myxvisual** [comment]
这个 issue 应该可以关闭吧

**Comment by JayceZhang9602** [comment]
完全加载之后效果好很多，但换图的时候还是有明显卡顿。。。可能是设备性能限制，达不到60fps难受=。=
<img width="1274" alt="2017-06-20 8 37 07" src="https://user-images.githubusercontent.com/20334140/27333390-49050bb0-55f8-11e7-913b-c4b8f8f1138e.png">
ps: 星型和心型打分组件，填充和鼠标点击位置有偏移；
      DropdownMenu, Menu, DatePickers 应该有 blur 事件或者提供关闭接口吧，目前点击页面其他区域不会关闭；
     顶部 Nav 非折叠状态下，Documentation href 为 /components，只有窗口宽度小于960出现折叠Nav点击组件名才能看到文档啊！！！！！

**Comment by myxvisual** [comment]
thanks, 这些会 issue 在下个版本修复~

**Comment by myxvisual** [comment]
@JayceZhang9602 修复打分组件的代码已经在 1.0.x 分支，会合并在下个版本一起发的~

**Comment by myxvisual** [comment]
@JayceZhang9602 现在所以组件都加了键盘响应和 blur 的交互了~ 发在 v1.0.5上了
