### ISSUE TITLE
License file appears to have a typo (MIT?)

### ISSUE THREAD

**Issue by darthtrevino** [myxvisual/react-uwp#26]
https://github.com/myxvisual/react-uwp/blob/master/LICENSE#L1

![screen shot 2017-10-23 at 1 14 58 pm](https://user-images.githubusercontent.com/113544/31911028-3490182e-b7f4-11e7-8d33-61a87b8c80c0.png)

![1000x563_386895](https://user-images.githubusercontent.com/113544/31911051-47934392-b7f4-11e7-9126-62d28cc9b779.jpg)

**Comment by myxvisual** [comment]
God, great mistake, thank you for pointing out.
