### ISSUE TITLE
Support for server side rendering(SSR)?

### ISSUE THREAD

**Issue by renshenhe** [myxvisual/react-uwp#3]
Trying to use the library on a server side rendered app but so far these errors have caused the app to crash.  
- `react-uwp/styles/fonts/segoe-mdl2-assets/index.js` uses document
- `react-uwp/Theme/index.js` uses `window`
- `react-uwp/common/prefixAll.js` uses `window` and `navigator`

There doesn't seem to be any webpack config to allow detection of environment so I just replaced the variables with empty objects for the time being to check it out.

**Comment by myxvisual** [comment]
sure~
i will add SSR to next version, thanks for feedback~
The next step，i will trying to add this library to cdnjs.

**Comment by myxvisual** [comment]
@renshenhe I tried running this [repository](https://github.com/myxvisual/react-uwp-ssr-example) and it worked fine~
