### ISSUE TITLE
Typings not working

### ISSUE THREAD

**Issue by michaelspeed** [myxvisual/react-uwp#34]
### Problem description
typings error  - 

> Cannot find namespace 'ReactUWP'.

` "typeRoots": [
      "./node_modules/@types",
      "./node_modules/react-uwp" // add to here.
    ],
    // ....
    "include": [
      "./node_modules/react-uwp/index.d.ts" // or add to here.
    ]`

both the above methods not working

- React-UWP:1.1.8
- React: 16.2.0
- Browser: Chrome

**Comment by myxvisual** [comment]
@michaelspeed hi, the readme is wrong example, this is the correct setting.

``` js
{
  "compilerOptions": {
    "typeRoots": [
      "./node_modules/@types"
    ],
    "filesGlob": [
      "**/*.ts",
      "**/*.tsx"
    ],
    "files": [
      "node_modules/react-uwp/index.d.ts" // add to here.
    ]
  }
}
```

**Comment by pboymt** [comment]
But I got a error in webpack said "cannot find namespace ReactUWP" when I used the config you said which is true.

**Comment by RohitLuthra19** [comment]
I also faced the same error  @pboymt  @michaelspeed @myxvisual

**Comment by oli-waymark** [comment]
Has anyone managed to resolve this issue I am also receiving the "Cannot find namespace 'ReactUWP'." error with the suggested config. @michaelspeed @RohitLuthra19   @myxvisual  @pboymt
