### ISSUE TITLE
im new player to react, and have a template project?

### ISSUE THREAD

**Issue by blueisboy** [myxvisual/react-uwp#35]
### Versions

- React-UWP: head
- React: none
- Browser: Microsoft edge

**Comment by blueisboy** [comment]
or groups?

**Comment by blueisboy** [comment]
is anyone here?

**Comment by myxvisual** [comment]
@blueisboy Hi, sorry about the delay in reply, this only maintainer of this project are me, if you like it and want to devote some ideas, you can send a PR to this repository, I will review the code, thanks.
