### ISSUE TITLE
Get TS2320 and TS2415 in webpack with awesome-typescript-loader.

### ISSUE THREAD

**Issue by pboymt** [myxvisual/react-uwp#37]
### Problem description
Get TS2320 and TS2415 in webpack with awesome-typescript-loader.

### Link to minimal working code that reproduces the issue
My code is same to this  #issue:https://github.com/myxvisual/react-uwp/issues/36

### Versions

- React-UWP: 1.1.8
- React:16.2
- Browser: Electron

```
ERROR in [at-loader] ./node_modules/react-uwp/CheckBox/index.d.ts:13:18
    TS2320: Interface 'CheckBoxProps' cannot simultaneously extend types 'DataProps' and 'HTMLAttributes<HTMLDivElement>'.
  Named property 'defaultChecked' of types 'DataProps' and 'HTMLAttributes<HTMLDivElement>' are not identical.

ERROR in [at-loader] ./node_modules/react-uwp/ScrollBar/index.d.ts:19:22
    TS2415: Class 'ScrollBar' incorrectly extends base class 'Component<ScrollBarProps, ScrollBarState>'.
  Types of property 'refs' are incompatible.
    Type '{ view?: HTMLDivElement | undefined; thumb?: HTMLDivElement | undefined; }' is not assignable to type '{ [key: string]: ReactInstance; }'.
      Property 'view' is incompatible with index signature.
        Type 'HTMLDivElement | undefined' is not assignable to type 'ReactInstance'.
          Type 'undefined' is not assignable to type 'ReactInstance'.
```

**Comment by arjunkrishna** [comment]
received the same error when trying this module on dotnet reactredum template.
[errorText.txt](https://github.com/myxvisual/react-uwp/files/2098899/errorText.txt)

dotnet new reactredux
SET ASPNETCORE_Environment=Development
cd ClientApp
npm install --save react-uwp
npm install --save react@^16.0.0 react-dom@^16.0.0
npm install npm@latest -g
added the following line to tsconfig
"files": [
      "node_modules/react-uwp/index.d.ts" // add to here.
    ],
dotnet build 
dotnet run
--error
