### ISSUE TITLE
Broken fonts and images

### ISSUE THREAD

**Issue by jaydson** [myxvisual/react-uwp#6]
### Problem description
There some broken fonts and images on the website (not sure if this is the right repo for reporting).

```
https://www.react-uwp.com/HEAD/static/segmdl2.woff2   
https://www.react-uwp.com/HEAD/static/segmdl2.woff   
https://www.react-uwp.com/HEAD/static/segmdl2.ttf  
```

**Comment by myxvisual** [comment]
@jaydson Thanks for feedback, the problem with other platform font icons should be the wrong font path.

**Comment by myxvisual** [comment]
@jaydson The public css is update now, [segoe-mdl2-assets.css](https://github.com/myxvisual/react-uwp/blob/gh-pages/HEAD/static/css/segoe-mdl2-assets.css), the broken images, do you have any filename or url？

**Comment by jaydson** [comment]
Hi @myxvisual, it seems like everything is Ok now.
Thank you :fist_oncoming:
