### ISSUE TITLE
Unable to get property 'toLowercase' of undefined or null reference 

### ISSUE THREAD

**Issue by ShrinathGupta** [myxvisual/react-uwp#60]
### Problem description
Build getting failed when deployed on react-native for windows. 
It shows error in `...\node_modules\react-uwp\common\electron\IS_ELECTRON_ENV.js`

I debugged and found that navigator does not have userAgent object, because if this it throws undefined.

### Link to minimal working code that reproduces the issue
```
import * as React from "react";
import { Theme as UWPThemeProvider, getTheme } from "react-uwp/Theme";
import Button from "react-uwp/Button";
const theme = getTheme({
  themeName: "dark",
  accent: "#0078D7",
  useFluentDesign: true,
  desktopBackgroundImage: "http://127.0.0.1:8092/static/images/jennifer-bailey-10753.jpg"
  userAgent: req.headers['user-agent']
});

export class App extends React.Component {
  render() {
    return (
      <UWPThemeProvider
        theme={theme}
        needGenerateAcrylic={false} // if using SSR, set this config to false, using fallback color.
      >
        <Button>Server Side Rendering...</Button>
      </UWPThemeProvider>
    )
  }
}
export default App;

```

![error](https://user-images.githubusercontent.com/12642711/46148106-ef3ca200-c284-11e8-8c9b-111e7f179ebd.jpg)

### Versions

- React-UWP: '^1.2.1'
- React:"16.5.0"
- Browser: "UWP app"

I have tried lot of things but it's not working.

@myxvisual Your help will be highly appreciated. !

**Comment by myxvisual** [comment]
Hi @ShrinathGupta thanks for feedback, sorry for neglecting this error, now you can upgrade to v1.2.2 to solve this problem.

**Comment by myxvisual** [comment]
Hi @ShrinathGupta thanks for feedback, sorry for neglecting this error, now you can upgrade to v1.2.2 to solve this problem.

**Comment by myxvisual** [comment]
Hi @ShrinathGupta thanks for feedback, sorry for neglecting this error, now you can upgrade to v1.2.2 to solve this problem.

**Comment by ShrinathGupta** [comment]
Thanks, but i tired that also and it breaks at `react-dom `module, 
Error: Object doesn't support property or method 'addeventlistner',
![error2](https://user-images.githubusercontent.com/12642711/46184275-7a07b600-c2f2-11e8-9e92-b64f9f66d64f.jpg)

`If i tried to remove, react-dom it breaks at module dependency 'Scrollreveal/index.js'
`So, I manually commented eventlistener in schedule.development.js. 
```
  // Assumes that we have addEventListener in this environment. Might need
  // something better for old IE.
  // window.addEventListener('message', idleTick, false);
```
After doing that still facing issue, please refer below attached image.
![error3](https://user-images.githubusercontent.com/12642711/46184736-8e4cb280-c2f4-11e8-81b0-5ed89322d203.jpg)

One more thing if i pass  ` userAgent: req.headers['user-agent']`, error occured: req is not defined.

@myxvisual can you please check where it starts breaking.
