### ISSUE TITLE
Table or Grid component

### ISSUE THREAD

**Issue by PitterL** [myxvisual/react-uwp#68]
Hi, Myxvisual:

May i understand how to achieve the table components in react-uwp?
I saw in your official document, there is a lot of table elements <table> <tr> <td> in web page, but not found the introduction. If that, is the 'span' attribute is supported ?

BTW, is there any official QQ or Wechat Group for React-UWP?
Thanks

**Comment by myxvisual** [comment]
@PitterL Hi, these table elements is genreated by [MarkdownRender](https://www.react-uwp.com/components/MarkdownRender).

**Comment by PitterL** [comment]
Hi, Myxvisual:
     Is more details to describe the MarkdownRender? My purpose is to achieve the components(Input/Button/...) into the grid cell.

Thanks
