### ISSUE TITLE
StyleManager always set style in document.head

### ISSUE THREAD

**Issue by Jack-Works** [myxvisual/react-uwp#73]
### Problem description

I'm mount my react component into a Shadow DOM. So all styles set by StyleManager can't affect my application. I want to have an option, to provide the ShadowRoot into the UWPThemeProvider.

### Versions

- React-UWP: latest
- React: latest
- Browser: latest chrome

**Comment by myxvisual** [comment]
@Jack-Works sorry for delay in reply, i checked the source code and found that it is possible to achieve your needs.
Under `ThemeWrapper`, you can use
``` js
const styleManagerCSSText = this.context.theme.styleManager.sheetsToString();
const otherCSSText = this.context.theme.styleManager.CSSText;
const allCSSText = styleManagerCSSText + otherCSSText ; // all you need CSSText.
```

**Comment by Jack-Works** [comment]
Oh cool, thanks
